apiVersion: v1
kind: ConfigMap
metadata:
 labels:
   app: {{ .Values.app.nginx.name }}
   component: filebeat
 name: {{ .Values.app.nginx.name }}-filebeat-sidecar-config
 namespace: {{ .Values.namespace }}
data:
  filebeat.yml: |
    filebeat:
      config:
        modules:
          path: /usr/share/filebeat/modules.d/*.yml
          reload:
            enabled: true
      modules:
      - module: nginx
        access:
          enabled: true
          var.paths:
          - "/var/log/nginx/access.log"
        error:
          enabled: true
          var.paths:
          - "/var/log/nginx/error.log"
    output:
      elasticsearch:
        host: '${NODE_NAME}'
        hosts: '${ELASTICSEARCH_HOSTS}:9200'

---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Values.app.nginx.name }}
  name: {{ .Values.app.nginx.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app.nginx.name }}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Values.app.nginx.name }}
    spec:
      containers:
      - name: {{ .Values.app.filebeat.name }}
        image: {{ .Values.app.filebeat.image }}
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: ELASTICSEARCH_HOSTS
          value: {{ .Values.app.elasticsearch.name }}
        volumeMounts:
        - name: logs-volume
          mountPath: /var/log/nginx
        - name: filebeat-config
          mountPath: /usr/share/filebeat/filebeat.yml
          subPath: filebeat.yml
      - image: {{ .Values.app.nginx.image }}
        name: {{ .Values.app.nginx.name }}
        ports:
        {{- range .Values.app.nginx.ports }}
        - containerPort: {{ .port }}
        {{- end}}
        volumeMounts:
        - name: logs-volume
          mountPath: /var/log/nginx
        resources: {}
      volumes:
      - name: logs-volume
        emptyDir: {}
      - name: filebeat-config
        configMap:
          name: {{ .Values.app.nginx.name }}-filebeat-sidecar-config
          items:
            - key: filebeat.yml
              path: filebeat.yml
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Values.app.nginx.name }}
  name: {{ .Values.app.nginx.name }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  {{- range .Values.app.nginx.ports }}
  - name: "{{ .port }}"
    port: {{ .port }}
    protocol: TCP
    targetPort: {{ .port }}
  {{- end }}
  selector:
    app: {{ .Values.app.nginx.name }}
  type: ClusterIP
status:
  loadBalancer: {}