apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Values.app.ldap.name }}
  name: {{ .Values.app.ldap.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.ldap.name }}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Values.app.ldap.name }}
    spec:
      containers:
      - image: {{ .Values.app.ldap.image.repository }}
        name: {{ .Values.app.ldap.name }}
        ports:
        {{- range .Values.app.ldap.service.ports }}
        - containerPort: {{ .port }}
        {{- end}}
        env:
        {{- range .Values.app.ldap.env }}
        - name: {{ .name}}
          value: {{ .value }}
        {{- end}}
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/ldap
          name: {{ .Values.app.ldap.volumes.ldap.name }}
        - mountPath: /etc/ldap/slapd.d
          name: {{ .Values.app.ldap.volumes.slapd.name }}
      volumes:
      - name: {{ .Values.app.ldap.volumes.ldap.name }}
        persistentVolumeClaim:
          claimName: {{ .Values.app.ldap.volumes.ldap.name }}
      - name: {{ .Values.app.ldap.volumes.slapd.name }}
        persistentVolumeClaim:
          claimName: {{ .Values.app.ldap.volumes.slapd.name }}

status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Values.app.ldap.name }}
  name: {{ .Values.app.ldap.name }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  {{- range .Values.app.ldap.service.ports }}
  - name: "{{ .port }}"
    port: {{ .port }}
    protocol: TCP
    targetPort: {{ .port }}
  {{- end }}
  selector:
    app: {{ .Values.app.ldap.name }}
  type: {{ .Values.app.ldap.service.type }}
status:
  loadBalancer: {}


