apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Values.app }}
  name: {{ .Values.app }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app }}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Values.app }}
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        name: {{ .Values.app }}
        ports:
        {{- range .Values.service.ports }}
        - containerPort: {{ .port }}
        {{- end}}
        # env:
        # {{- range .Values.env }}
        # - name: {{ .name }}
        #   value: {{ .value }}
        # {{- end}}
        resources: {}
        volumeMounts:
        - mountPath: /nexus-data
          name: {{ .Values.app }}
      volumes:
      - name: {{ .Values.app }}
        persistentVolumeClaim:
          claimName: {{ .Values.app }}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Values.app }}
  name: {{ .Values.app }}-svc
  namespace: {{ .Values.namespace }}
spec:
  ports:
  {{- range .Values.service.ports }}
  - name: "{{ .port }}"
    port: {{ .port }}
    protocol: TCP
    targetPort: {{ .port }}
  {{- end }}
  selector:
    app: {{ .Values.app }}
  type: {{ .Values.service.type }}
status:
  loadBalancer: {}
