---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.app }}
  annotations:
    pv.beta.kubernetes.io/gid: "200"
spec:
  capacity:
    storage: {{ .Values.resources.storage.size }}
  volumeMode: Filesystem
  accessModes:
  - {{ .Values.resources.storage.access }}
  # persistentVolumeReclaimPolicy: {{ .Values.resources.storage.policy }}
  storageClassName: hostpath
  local:
    path: {{ .Values.resources.storage.path }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - latitude
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.app }}
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - {{ .Values.resources.storage.access }}
  volumeMode: Filesystem
  storageClassName: hostpath
  resources:
    requests:
      storage: {{ .Values.resources.storage.size }}
