apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.app }}-pv
spec:
  capacity:
    storage: {{ .Values.resources.storage.size }}
  volumeMode: Filesystem
  accessModes:
  - {{ .Values.resources.storage.access }}
  persistentVolumeReclaimPolicy: Delete
  storageClassName: {{ .Values.resources.storage.sc }}
  local:
    path: {{ .Values.resources.storage.path }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - latitude
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.app }}-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - {{ .Values.resources.storage.access }}
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.resources.storage.size }}
  storageClassName: {{ .Values.resources.storage.sc }}