apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Values.app }}
  name: {{ .Values.app }}-svc
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: {{ .Values.image.name }}
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.port }}
  selector:
    app: {{ .Values.app }}
  type: {{ .Values.service.type }}
status:
  loadBalancer: {}

